

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(400, 450)
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(217, 217, 158);")
        self.label.setLineWidth(2)
        self.label.setMidLineWidth(0)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 50, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(100, 50, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(200, 50, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(300, 50, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 150, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 150, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(200, 150, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(300, 150, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 250, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(100, 250, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(200, 250, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_umnoj = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_umnoj.setGeometry(QtCore.QRect(300, 250, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_umnoj.setFont(font)
        self.pushButton_umnoj.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_umnoj.setObjectName("pushButton_umnoj")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 350, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_ravno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ravno.setGeometry(QtCore.QRect(200, 350, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ravno.setFont(font)
        self.pushButton_ravno.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_ravno.setObjectName("pushButton_ravno")
        self.pushButton_delen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delen.setGeometry(QtCore.QRect(300, 350, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_delen.setFont(font)
        self.pushButton_delen.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_delen.setObjectName("pushButton_delen")
        self.pushButton_quar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quar.setGeometry(QtCore.QRect(100, 350, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quar.setFont(font)
        self.pushButton_quar.setStyleSheet("background-color: rgb(222, 222, 110);")
        self.pushButton_quar.setObjectName("pushButton_quar")
        Calculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

        self.add_functions()

        self.is_equel = False


    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.label.setText(_translate("Calculator", "0"))
        self.pushButton_11.setText(_translate("Calculator", "7"))
        self.pushButton_13.setText(_translate("Calculator", "8"))
        self.pushButton_17.setText(_translate("Calculator", "9"))
        self.pushButton_plus.setText(_translate("Calculator", "+"))
        self.pushButton_5.setText(_translate("Calculator", "4"))
        self.pushButton_6.setText(_translate("Calculator", "5"))
        self.pushButton_7.setText(_translate("Calculator", "6"))
        self.pushButton_minus.setText(_translate("Calculator", "-"))
        self.pushButton_1.setText(_translate("Calculator", "1"))
        self.pushButton_9.setText(_translate("Calculator", "2"))
        self.pushButton_10.setText(_translate("Calculator", "3"))
        self.pushButton_umnoj.setText(_translate("Calculator", "*"))
        self.pushButton_0.setText(_translate("Calculator", "0"))
        self.pushButton_ravno.setText(_translate("Calculator", "="))
        self.pushButton_delen.setText(_translate("Calculator", "/"))
        self.pushButton_quar.setText(_translate("Calculator", "**2"))

    def add_functions(self):
        self.pushButton_0.clicked.connect(lambda:  self.write_number(self.pushButton_0.text()))
        self.pushButton_1.clicked.connect(lambda: self.write_number(self.pushButton_1.text()))
        self.pushButton_9.clicked.connect(lambda: self.write_number(self.pushButton_9.text()))
        self.pushButton_10.clicked.connect(lambda: self.write_number(self.pushButton_10.text()))
        self.pushButton_5.clicked.connect(lambda: self.write_number(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(lambda: self.write_number(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(lambda: self.write_number(self.pushButton_7.text()))
        self.pushButton_11.clicked.connect(lambda: self.write_number(self.pushButton_11.text()))
        self.pushButton_13.clicked.connect(lambda: self.write_number(self.pushButton_13.text()))
        self.pushButton_17.clicked.connect(lambda: self.write_number(self.pushButton_17.text()))
        self.pushButton_plus.clicked.connect(lambda: self.write_number(self.pushButton_plus.text()))
        self.pushButton_minus.clicked.connect(lambda: self.write_number(self.pushButton_minus.text()))
        self.pushButton_umnoj.clicked.connect(lambda: self.write_number(self.pushButton_umnoj.text()))
        self.pushButton_delen.clicked.connect(lambda: self.write_number(self.pushButton_delen.text()))
        self.pushButton_quar.clicked.connect(lambda: self.write_number(self.pushButton_quar.text()))
        self.pushButton_ravno.clicked.connect(self.result)

    def write_number(self, number):
        if self.label.text() == "0" or self.is_equel:
            self.label.setText(number)
            self.is_equel = False
        else:
            self.label.setText(self.label.text() + number)

    def result(self):
        if not self.is_equel:
            res = eval(self.label.text())
            self.label.setText("  Результат: " + str(res))
            self.is_equel = True

        else:

            error = QMessageBox()
            error.setWindowTitle('Внимание')
            error.setText('Сначала введите числа и знаки действий')
            error.setIcon(QMessageBox.Warning)
            error.setStandardButton(QMessageBox.Ok|QMessageBox.Cancel)

            error.setDefaultButton(QMessageBox.Ok)

            error.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec())
